// import Navbar from '@/src/components/navbar'
import "./globals.css";
import { Inter } from "next/font/google";
import QueryClientWrapper from "@/src/utils/Wrapper/QueryClientWrapper";
import { cookies } from "next/headers";
import Footer from "@/src/infrastructure/ui/global/footer";

export const metadata = {
  title: "Mitrain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");

  return (
    <html data-theme="light" lang="en" suppressHydrationWarning>
      <body>
        <QueryClientWrapper token={token}>
          {" "}
          {/* subNavbar & navbar inside the queryClientWrapper */}
          {children}
          <Footer />
        </QueryClientWrapper>
      </body>
    </html>
  );
}
