import "./globals.css";
import QueryClientWrapper from "@/src/utils/Wrapper/QueryClientWrapper";
import { cookies } from "next/headers";
import ProgressProvider from "@/src/infrastructure/ui/global/provider/ProgressProvider";
import { Toaster } from "@/src/components/ui/toaster";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mitrain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");

  return (
    <html data-theme="light" lang="en" suppressHydrationWarning>
      <body className={inter.className + " no-scrollbar"}>
        <ProgressProvider>
          <QueryClientWrapper token={token}>
            {children}
            <Toaster />
          </QueryClientWrapper>
        </ProgressProvider>
      </body>
    </html>
  );
}
