'use client'

import Navbar from '@/src/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/src/components/footer'
import { QueryClient, QueryClientProvider } from "react-query";
import { useEffect, useState } from 'react'
import { decodeToken } from '@/src/utils/auth/decodeToken'


export const metadata = {
  title: 'Mitrain',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const queryClient = new QueryClient();

  return (
    <html data-theme="light" lang="en">
      <QueryClientProvider client={queryClient}>
        <body>
          <Navbar  />
          {children}
          <Footer />
        </body>
      </QueryClientProvider>
    </html>
  )
}
